"""update_idempotency_keys_user_id

Revision ID: 9caf9bf12efb
Revises: 001_initial
Create Date: 2026-01-04 14:37:52.027790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caf9bf12efb'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_idempotency_keys_key', table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_idempotency_key', 'idempotency_keys', ['user_id', 'key'])
    op.create_foreign_key(None, 'idempotency_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_transactions_bank_reference', table_name='transactions')
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'transactions', ['bank_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.create_index('ix_transactions_bank_reference', 'transactions', ['bank_reference'], unique=True)
    op.drop_constraint(None, 'idempotency_keys', type_='foreignkey')
    op.drop_constraint('unique_user_idempotency_key', 'idempotency_keys', type_='unique')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.create_index('ix_idempotency_keys_key', 'idempotency_keys', ['key'], unique=True)
    op.drop_column('idempotency_keys', 'user_id')
    # ### end Alembic commands ###
